# Use postgres/example user/password credentials
#version: '3.1'
version: '3.8'

services:

  cnam-mysql:
    image: mysql:8.0.33
    container_name: cnam-mysql
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD : admin
